list: $/reportertool/eokm/models/manual/columns.yaml
modelClass: ReporterTool\EOKM\Models\Manual
title: Manualedit
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'reportertool/eokm/manualedit/update/:id'
