name: Import
modelClass: ReporterTool\EOKM\Models\Input_import
form: $/reportertool/eokm/models/input_import/fields.yaml
defaultRedirect: 'reportertool/eokm/Inputs_import/create'
create:
    title: Import file
    redirect: 'reportertool/eokm/Inputs_import/update/:id'
    redirectClose: reportertool/eokm/Inputs
update:
    title: File imported
    redirect: reportertool/eokm/import/create
    redirectClose: reportertool/eokm/Inputs
preview: {  }
