name: Changed
form: $/reportertool/eokm/models/inputnotification/fields.yaml
modelClass: ReporterTool\EOKM\Models\Inputnotification
defaultRedirect: reportertool/eokm/changed
create:
    redirect: 'reportertool/eokm/changed/update/:id'
    redirectClose: reportertool/eokm/changed
update:
    redirect: reportertool/eokm/changed
    redirectClose: reportertool/eokm/changed
