list: $/reportertool/eokm/models/manual/columns_readonly.yaml
modelClass: ReporterTool\EOKM\Models\Manual
title: Manual
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: false
showCheckboxes: false
showSorting: true
defaultSort: chapter
recordsPerPage: 30
toolbar:
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'reportertool/eokm/manual/preview/:id'
