name: Domainrule
modelClass: ReporterTool\EOKM\Models\Domainrule
form: $/reportertool/eokm/models/domainrule/fields.yaml
defaultRedirect: reportertool/eokm/domainrule
create:
    redirect: 'reportertool/eokm/domainrule/update/:id'
    redirectClose: reportertool/eokm/domainrule
update:
    redirect: reportertool/eokm/domainrule
    redirectClose: reportertool/eokm/domainrule
preview: {  }
