list: $/reportertool/eokm/models/blockedday/columns.yaml
modelClass: ReporterTool\EOKM\Models\Blockedday
title: Blockeddays
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'reportertool/eokm/blockeddays/update/:id'
