# ===================================
#  Import Behavior Config
# ===================================

import:
  title: Import
  form: $/reportertool/eokm/models/input_import/bulk_fields.yaml
  modelClass: ReporterTool\EOKM\Models\Input_bulkimport
  list: $/reportertool/eokm/models/input_import/bulk_columns.yaml
  redirect: reportertool/eokm/inputs
