logs:
  label: log
  modelClass: reportertool\eokm\models\Log
  readOnly: true
  view:
    list: $/reportertool/eokm/models/log/columns.yaml
    showSorting: false
    recordsPerPage: 5
notifications:
  label: notification
  modelClass: reportertool\eokm\models\Notification
  readOnly: false
  view:
    list: $/reportertool/eokm/models/input/columns_notification.yaml
    showCheckboxes: false
    toolbarButtons: create
    showSorting: false
    showSearching: true
    recordsPerPage: 5
  manage:
    form: $/reportertool/eokm/models/input/fields_notification.yaml
    list: $/reportertool/eokm/models/input/columns_notification.yaml
