name: Inputs
form: $/reportertool/eokm/models/input/fields.yaml
modelClass: ReporterTool\EOKM\Models\Input
defaultRedirect: reportertool/eokm/inputs
create:
    redirect: 'reportertool/eokm/inputs/update/:id'
    redirectClose: reportertool/eokm/inputs
update:
    redirect: reportertool/eokm/inputs
    redirectClose: reportertool/eokm/inputs
