plugin:
    name: 'reportertool.eokm::lang.plugin.name'
    description: 'reportertool.eokm::lang.plugin.description'
    author: AbuseIO
    icon: oc-icon-check
    homepage: 'https://abuse.io/'
navigation:
    Startpage:
        label: Startpage
        url: /reportertool/eokm/Startpage
        icon: icon-dashboard
        order: '1'
    Inputs:
        label: Input
        url: /reportertool/eokm/Inputs
        icon: icon-file-photo-o
        order: '2'
    Grade:
        label: Classify
        url: /reportertool/eokm/Grade
        icon: icon-check-circle
        order: '3'
    Police:
        label: Police
        url: /reportertool/eokm/Police
        icon: icon-warning
        order: '4'
    NTD:
        label: 'NTD''s'
        url: /reportertool/eokm/ntds
        icon: icon-external-link
        order: '5'
    Changed:
        label: Changed
        url: /reportertool/eokm/Changed
        icon: icon-user-circle
        order: '6'
    Abusecontacts:
        label: 'Abuse contacts'
        url: /reportertool/eokm/Abusecontacts
        icon: icon-group
        permissions:
            - reportertool.eokm.abusecontact_manage
        order: '7'
    Report:
        label: Report
        url: /reportertool/eokm/report
        icon: icon-image
        permissions:
            - reportertool.eokm.reporting
        order: '8'
    Domainrules:
        label: Rules
        url: /reportertool/eokm/domainrule
        icon: icon-list-ul
        order: '9'
    utility:
        label: Settings
        url: /reportertool/eokm/NTDtemplates
        icon: icon-gears
        permissions:
            - reportertool.eokm.utility
        order: '10'
        sideMenu:
            NTDtemplates:
                label: 'NTD Templates'
                url: /reportertool/eokm/NTDtemplates
                icon: icon-files-o
                permissions:
                    - reportertool.eokm.ntdtemplate_manage
                order: '1'
            GradeQuestions:
                label: GradeQuestions
                url: /reportertool/eokm/Grade_questions
                icon: icon-table
                permissions:
                    - reportertool.eokm.grade_questions
                order: '2'
            whois:
                label: 'WhoIs test'
                url: /reportertool/eokm/Whois
                icon: icon-file-archive-o
                permissions:
                    - reportertool.eokm.whois
                order: '3'
            manualedit:
                label: 'Manual EDIT'
                url: /reportertool/eokm/Manualedit
                icon: icon-book
                permissions:
                    - reportertool.eokm.manual_write
            Blockedday:
                label: 'Blocked days'
                url: /reportertool/eokm/Blockeddays
                icon: icon-birthday-cake
