title: Notifications
modelClass: ReporterTool\EOKM\Models\Notification
list: $/reportertool/eokm/models/notification/columns.yaml
recordUrl: 'reportertool/eokm/report/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
defaultSort: updated_at desc
filter: config_filter.yaml
toolbar:
  buttons: list_toolbar
  search:
    prompt: 'backend::lang.list.search_prompt'

