title: Abusecontacts
modelClass: ReporterTool\EOKM\Models\Abusecontact
list: $/reportertool/eokm/models/abusecontact/columns.yaml
recordUrl: 'reportertool/eokm/abusecontacts/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
