name: Abusecontacts
modelClass: ReporterTool\EOKM\Models\Abusecontact
form: $/reportertool/eokm/models/abusecontact/fields.yaml
defaultRedirect: reportertool/eokm/abusecontacts
create:
    redirect: 'reportertool/eokm/abusecontacts/update/:id'
    redirectClose: reportertool/eokm/abusecontacts
update:
    redirect: reportertool/eokm/abusecontacts
    redirectClose: reportertool/eokm/abusecontacts
preview: {  }
