title: Classify
list: $/reportertool/eokm/models/input/columns_grade.yaml
modelClass: ReporterTool\EOKM\Models\Input
recordUrl: 'reportertool/eokm/grade/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
filter: config_filter.yaml
recordsPerPage: 20
showSetup: false
showCheckboxes: true
defaultSort: filenumber asc
toolbar:
  buttons: list_toolbar
  search:
    prompt: 'backend::lang.list.search_prompt'
