name: NTDtemplates
form: $/reportertool/eokm/models/ntdtemplate/fields.yaml
modelClass: ReporterTool\EOKM\Models\NTDtemplate
defaultRedirect: reportertool/eokm/ntdtemplates
create:
    redirect: 'reportertool/eokm/ntdtemplates/update/:id'
    redirectClose: reportertool/eokm/ntdtemplates
update:
    redirect: reportertool/eokm/ntdtemplates
    redirectClose: reportertool/eokm/ntdtemplates
