list: $/reportertool/eokm/models/ntdtemplate/columns.yaml
modelClass: ReporterTool\EOKM\Models\NTDtemplate
title: NTDtemplates
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'reportertool/eokm/ntdtemplates/update/:id'
