name: Inputs
modelClass: ReporterTool\EOKM\Models\Ntd
form: $/reportertool/eokm/models/ntd/fields.yaml
defaultRedirect: reportertool/eokm/ntd
create:
    redirect: 'reportertool/eokm/ntd/preview/:id'
    redirectClose: reportertool/eokm/ntd
update:
    redirect: reportertool/eokm/ntd
    redirectClose: reportertool/eokm/ntd
preview: {  }
