logs:
  label: log
  modelClass: reportertool\eokm\models\Log
  readOnly: true
  view:
    list: $/reportertool/eokm/models/log/columns.yaml
    showSorting: false
    recordsPerPage: 5
ntd_urls:
  label: ntd_urls
  modelClass: reportertool\eokm\models\Ntd_url
  readOnly: true
  view:
    list: $/reportertool/eokm/models/ntd/columns_ntd_urls.yaml
    showCheckboxes: false
    showSorting: false
    recordsPerPage: 10
