# ===================================
#  Export Behavior Config
# ===================================

defaultFormatOptions:
  delimiter: ';'
  enclosure: '"'
  escape: '\'

export:
  title: Export NTD
  fileName: exportNTD.csv
  modelClass: ReporterTool\EOKM\Models\NtdExport
  form: $/reportertool/eokm/models/ntdexport/fields.yaml
  list: $/reportertool/eokm/models/ntdexport/columns.yaml
  redirect: reportertool/eokm/ntds
