title: NTDs
modelClass: ReporterTool\EOKM\Models\Ntd
list: $/reportertool/eokm/models/ntd/columns.yaml
recordUrl: 'reportertool/eokm/ntds/preview/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: false
showCheckboxes: false
defaultSort: 'filenumber asc'
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
filter: config_filter.yaml
